export const forestSlices = [
  { key: 'average-tree', filename: 'average-tree.png' },
  { key: 'bush', filename: 'bush.png' },
  { key: 'ground-snow', filename: 'ground-snow.png' },
  { key: 'house-1', filename: 'house-1.png' },
  { key: 'house-2', filename: 'house-2.png' },
  { key: 'house-3', filename: 'house-3.png' },
  { key: 'house-4', filename: 'house-4.png' },
  { key: 'sign-left', filename: 'sign-left.png' },
  { key: 'sign-right', filename: 'sign-right.png' },
  { key: 'snowdrift', filename: 'snowdrift.png' },
  { key: 'snowdrift-2', filename: 'snowdrift-2.png' },
  { key: 'snowdrop-1', filename: 'snowdrop-1.png' },
  { key: 'snowdrop-2', filename: 'snowdrop-2.png' },
  { key: 'snowman', filename: 'snowman.png' },
  { key: 'toilet', filename: 'toilet.png' },
  { key: 'tree-1', filename: 'tree-1.png' },
  { key: 'tree-2', filename: 'tree-2.png' },
  { key: 'tree-3', filename: 'tree-3.png' },
  { key: 'tree-4', filename: 'tree-4.png' },
  { key: 'tree-5', filename: 'tree-5.png' },
  { key: 'tree-6', filename: 'tree-6.png' },
] as const;

export const forestForegroundGroundKeys = [
  'ground-snow',
  'snowdrift',
  'snowdrift-2',
  'snowdrop-1',
  'snowdrop-2',
] as const;

export const forestForegroundPropKeys = [
  'house-1',
  'house-2',
  'house-3',
  'house-4',
  'snowman',
  'bush',
  'sign-left',
  'sign-right',
  'toilet',
  'average-tree',
  'tree-1',
  'tree-2',
  'tree-3',
  'tree-4',
  'tree-5',
  'tree-6',
] as const;
